server:
  port: 8400

spring:
  data:
    redis:
      host: localhost
      port: 6379

queue:
  active-limit: 5

jwt:
  secret: FbmK3WfZF1XyToIlNr-LANTHKDVLL1lgiXp_IWJ8dsEMkWjv9ycIoa2qMNK7KDYy2xNPio19Og2tV6jWsXIElg
  ttl-minutes: 20m