server:
  port: 8400

spring:
  application:
    name: queue-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: "queue-service"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

queue:
  active-limit: 5

jwt:
  secret: ${JWT_SECRET}
  ttl-minutes: 1m