server:
  port: 8600

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/popcorn
    driver-class-name: org.postgresql.Driver
    username: luckyvicky
    password: luckyvicky
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: user-service