ARG MODULE

FROM gradle:8.7-jdk17 AS build
ARG MODULE
WORKDIR /workspace
COPY . .
RUN gradle :${MODULE}:bootJar -x test --no-daemon

FROM eclipse-temurin:17-jre
ARG MODULE
WORKDIR /app
COPY --from=build /workspace/${MODULE}/build/libs/*.jar app.jar
EXPOSE 8400
ENTRYPOINT ["java","-jar","/app/app.jar"]

